root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o tmp/server ./cmd/server/"
bin = "tmp/server"
full_bin = "sh -c 'cd /home/jingle/opc/bid-maker/backend && ./tmp/server'"
include_ext = ["go"]
exclude_dir = ["tmp", "vendor"]
delay = 500
stop_on_error = true

[log]
time = false

[color]
main = "yellow"
stub = "magenta"
runner = "green"
winner = "cyan"
