root = "."
tmp_dir = "tmp"

[build]
cmd = "go build ./cmd/server/"
bin = "tmp/server"
full_bin = "tmp/server"
include_ext = ["go", "mod"]
exclude_dir = ["tmp", "vendor"]
delay = 100

[log]
time = false

[color]
main = "yellow"
stub = "magenta"
runner = "green"
winner = "cyan"
